version: '3.1'

services:

  events-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DATABASE_PASSWORD}

  events:
    image: eventgo
    depends_on:
    - events-db
    ports:
    - 80:8080