spring:
  application:
    name: event-registration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"